[package]
name = "kvs"
version = "0.1.0"
authors = ["Arash Outadi <aoutadi@infoblox.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
clap = "*"