[package]
name = "kvs"
version = "0.1.0"
authors = ["Arash Outadi <aoutadi@infoblox.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
clap = "*"
structopt = "*"
predicates = "1.0.0"
tempfile = "3.0.7"
walkdir = "2.2.7"